language: go
go:
- 1.11.x
env:
- PATH=$HOME/protoc/bin:$PATH
before_install:
- openssl aes-256-cbc -K $encrypted_4e0cc4f50b4d_key -iv $encrypted_4e0cc4f50b4d_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- export GO111MODULE=on
script:
- make build
after_success:
- chmod 600 ~/.ssh/id_rsa
- docker login -u="$DOCKER_NAME" -p="$DOCKER_PWD"
- docker build -t sundogrd/content-grpc:$TRAVIS_BRANCH-$TRAVIS_BUILD_ID .
- docker push sundogrd/content-grpc:$TRAVIS_BRANCH-$TRAVIS_BUILD_IDgit
- ssh root@118.25.150.3 -o StrictHostKeyChecking=no 'cd ~/workspace && test ! -f content-grpc/devops/deploy.sh
  && (rm -rf content-grpc && git clone https://github.com/sundogrd/content-grpc.git ) || echo Bingo && cd content-grpc
  && git pull && git checkout master && git branch | grep -v "master" | xargs git branch -D && git checkout -b $TRAVIS_BRANCH origin/$TRAVIS_BRANCHcd && sh ./devops/deploy.sh' $TRAVIS_BRANCH
  $TRAVIS_BUILD_ID
branches:
  only:
    - master